name: 🔒 Security Vulnerability
description: Report a security vulnerability (for non-critical issues only)
title: '[Security]: '
labels: ['security', 'needs-triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Important Security Notice

        **For critical security vulnerabilities**, please do NOT use this form. Instead:
        - Use GitHub's private vulnerability reporting feature
        - Or email security@example.com

        This form is for **low-severity security issues** that are safe to discuss publicly.

  - type: checkboxes
    id: severity-check
    attributes:
      label: Severity Confirmation
      description: Please confirm this is appropriate for public disclosure
      options:
        - label: This is a LOW severity issue that is safe to discuss publicly
          required: true
        - label: This issue does NOT expose sensitive data or allow unauthorized access
          required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      options:
        - Information Disclosure (Low)
        - Configuration Issue
        - Deprecated Dependency
        - Documentation Gap
        - Other (Low Severity)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security issue
      placeholder: A clear description of the security issue...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this issue?
      placeholder: Describe the potential impact...
    validations:
      required: true

  - type: textarea
    id: remediation
    attributes:
      label: Suggested Remediation
      description: If you have suggestions for fixing this issue, please share them
      placeholder: Possible solutions...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant CVEs, articles, or documentation
      placeholder: Links to relevant resources...




